In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import pathlib
import array
import matplotlib.pyplot as plt
from keras.regularizers import l1,l2
from tensorflow import feature_column
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from keras.wrappers.scikit_learn import KerasClassifier
from keras.layers import Dense
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout

from numpy.random import seed
import random

In [2]:
train = pd.read_csv("../input/a-not-a/A.csv")
train

,Age_Raw,Age,Sex,Ethnic_Category,IMD_Score_Raw,IMD_Group,Attend_Status
0,73,70-79,Male,A,41.866,>= 34.17,Attended
1,56,50-59,Female,A,44.572,>= 34.17,Attended
2,70,70-79,Male,A,16.161,13.8-21.35,Attended
3,27,20-29,Female,A,12.683,8.5-13.79,Attended
4,65,60-69,Female,A,14.490,13.8-21.35,Attended
...,...,...,...,...,...,...,...
770201,42,40-49,Male,A,11.548,8.5-13.79,Attended
770202,92,90,Male,A,17.518,13.8-21.35,Attended
770203,16,10-19,Male,A,17.524,13.8-21.35,DNA
770204,89,80-89,Female,A,11.392,8.5-13.79,Attended
770205,71,70-79,Female,A,19.609,13.8-21.35,Attended

In [3]:
train.Attend_Status[train.Attend_Status == 'Attended'] = 0
train.Attend_Status[train.Attend_Status == 'DNA'] = 1

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [4]:
train1= pd.read_csv('../input/a-not-a/A.csv', usecols=['Sex','Attend_Status'])
train1

           Sex Attend_Status
0         Male      Attended
1       Female      Attended
2         Male      Attended
3       Female      Attended
4       Female      Attended
...        ...           ...
770201    Male      Attended
770202    Male      Attended
770203    Male           DNA
770204  Female      Attended
770205  Female      Attended

[770206 rows x 2 columns]

In [5]:
train1.Attend_Status[train1.Attend_Status == 'Attended'] = 0
train1.Attend_Status[train1.Attend_Status == 'DNA'] = 1
train1.Sex[train1.Sex== 'Male'] = 0
train1.Sex[train1.Sex == 'Female'] = 1
train1

       Sex Attend_Status
0        0             0
1        1             0
2        0             0
3        1             0
4        1             0
...     ..           ...
770201   0             0
770202   0             0
770203   0             1
770204   1             0
770205   1             0

[770206 rows x 2 columns]

In [6]:
sum(train1.Attend_Status)/len(train1)

0.07988252493488755